# Basic PyTorch

In [1]:
import torch
import numpy as np

In [2]:
torch.__version__, np.__version__

('0.3.0.post4', '1.14.0')

### Basic n-dimensionaly array

In [3]:
a = np.ndarray((5, 3))

In [4]:
a

array([[-2.68156159e+154, -2.68156159e+154,  3.95252517e-323],
       [ 0.00000000e+000,  0.00000000e+000,  0.00000000e+000],
       [ 0.00000000e+000,  0.00000000e+000,  0.00000000e+000],
       [ 0.00000000e+000,  0.00000000e+000,  0.00000000e+000],
       [ 0.00000000e+000,  0.00000000e+000, -2.00389837e+000]])

In [5]:
a.shape

(5, 3)

In [6]:
b = torch.Tensor(5, 3)

In [7]:
b


 0.0000e+00 -3.6893e+19  0.0000e+00
-3.6893e+19  1.4013e-44  0.0000e+00
 0.0000e+00  0.0000e+00  0.0000e+00
 0.0000e+00  0.0000e+00  0.0000e+00
 0.0000e+00  0.0000e+00  0.0000e+00
[torch.FloatTensor of size 5x3]

In [8]:
b.shape

torch.Size([5, 3])

### Random initialization

In [9]:
a = np.random.random((5, 3))

In [10]:
a

array([[0.93383011, 0.97619324, 0.91292588],
       [0.45280846, 0.36910305, 0.92698284],
       [0.64546573, 0.44480753, 0.53005201],
       [0.78500436, 0.02169228, 0.35674537],
       [0.49651987, 0.40912094, 0.01239978]])

In [11]:
b = torch.rand(5, 3)

In [12]:
b


 0.6917  0.5760  0.2628
 0.9539  0.0038  0.7936
 0.8270  0.8851  0.2065
 0.6867  0.3029  0.6871
 0.9155  0.9480  0.1354
[torch.FloatTensor of size 5x3]

In [13]:
a.size, b.size()

(15, torch.Size([5, 3]))

### Operations

In [14]:
x = torch.rand(5, 3)
y = torch.rand(5, 3)

In [15]:
x


 0.7612  0.4093  0.8793
 0.9282  0.1877  0.9253
 0.9217  0.8668  0.5678
 0.3743  0.4118  0.1228
 0.6076  0.9975  0.9292
[torch.FloatTensor of size 5x3]

In [16]:
y


 0.9717  0.7190  0.4087
 0.9428  0.3442  0.9098
 0.8670  0.9194  0.6477
 0.9791  0.3276  0.0120
 0.8541  0.9114  0.6267
[torch.FloatTensor of size 5x3]

In [21]:
%timeit x + y

1.53 µs ± 24.1 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [22]:
%timeit torch.add(x, y) # Functional form.

1.75 µs ± 42.6 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [23]:
y.add_(x) # inplace


 1.7329  1.1283  1.2880
 1.8710  0.5319  1.8352
 1.7887  1.7862  1.2156
 1.3534  0.7394  0.1348
 1.4617  1.9089  1.5559
[torch.FloatTensor of size 5x3]

In [24]:
y


 1.7329  1.1283  1.2880
 1.8710  0.5319  1.8352
 1.7887  1.7862  1.2156
 1.3534  0.7394  0.1348
 1.4617  1.9089  1.5559
[torch.FloatTensor of size 5x3]

### Indexing as in numpy

In [25]:
x


 0.7612  0.4093  0.8793
 0.9282  0.1877  0.9253
 0.9217  0.8668  0.5678
 0.3743  0.4118  0.1228
 0.6076  0.9975  0.9292
[torch.FloatTensor of size 5x3]

In [26]:
x[:, 1]


 0.4093
 0.1877
 0.8668
 0.4118
 0.9975
[torch.FloatTensor of size 5]

In [27]:
x[2, :]


 0.9217
 0.8668
 0.5678
[torch.FloatTensor of size 3]

In [28]:
x[2, 1]

0.866794764995575

### Reshape

In [29]:
x = torch.randn(4, 4)

In [30]:
x


 0.9133  0.6681 -1.1740 -1.5985
 0.2599  1.6053  0.2690 -0.5606
-1.7714 -0.3938 -0.2812  0.6922
-0.1262 -0.4839 -2.3440 -0.0457
[torch.FloatTensor of size 4x4]

In [32]:
x.view(16) # np.reshape


 0.9133
 0.6681
-1.1740
-1.5985
 0.2599
 1.6053
 0.2690
-0.5606
-1.7714
-0.3938
-0.2812
 0.6922
-0.1262
-0.4839
-2.3440
-0.0457
[torch.FloatTensor of size 16]

### Switch between tensor and ndarray

In [33]:
torch.zeros(5) # np.zeros


 0
 0
 0
 0
 0
[torch.FloatTensor of size 5]

In [34]:
a = torch.ones(5) # np.ones
a


 1
 1
 1
 1
 1
[torch.FloatTensor of size 5]

In [35]:
type(a)

torch.FloatTensor

In [36]:
b = a.numpy()

Fast, only metadata is moved.

In [37]:
type(b)

numpy.ndarray

In [39]:
b[0] += 1

In [40]:
a


 2
 1
 1
 1
 1
[torch.FloatTensor of size 5]

### Vice Versa

In [41]:
a = np.ones(5)

In [42]:
type(a)

numpy.ndarray

In [43]:
b = torch.from_numpy(a)

In [44]:
b


 1
 1
 1
 1
 1
[torch.DoubleTensor of size 5]

In [45]:
np.add(a, 1, out=a) # inline add 1

array([2., 2., 2., 2., 2.])

In [46]:
b


 2
 2
 2
 2
 2
[torch.DoubleTensor of size 5]

In [47]:
x = torch.rand(10)
y = torch.rand(10)

if torch.cuda.is_available():
    x = x.cuda()
    y = y.cuda()
    print(x + y)
else:
    print("cuda is not available")

cuda is not available
