# Basic PyTorch

In [4]:
import torch
import numpy as np

In [6]:
torch.__version__, np.__version__

('0.3.0.post4', '1.14.0')

### Basic n-dimensionaly array

In [12]:
a = np.ndarray((5, 3))

In [13]:
a

array([[ 2.00000000e+000,  2.00000000e+000,  3.95252517e-323],
       [ 0.00000000e+000,  0.00000000e+000,  0.00000000e+000],
       [ 0.00000000e+000,  0.00000000e+000,  0.00000000e+000],
       [ 0.00000000e+000,  0.00000000e+000,  0.00000000e+000],
       [ 0.00000000e+000,  2.00000000e+000, -3.11109737e+231]])

In [17]:
a.shape

(5, 3)

In [14]:
b = torch.Tensor(5, 3)

In [15]:
b


 0.0000  2.0000  0.0000
 2.0000  0.0000  0.0000
 0.0000  0.0000  0.0000
 0.0000  0.0000  0.0000
 0.0000  0.0000  0.0000
[torch.FloatTensor of size 5x3]

In [16]:
b.shape

torch.Size([5, 3])

### Random initialization

In [22]:
a = np.random.random((5, 3))

In [23]:
a

array([[0.07091735, 0.19294845, 0.42389628],
       [0.06972307, 0.00366603, 0.70787386],
       [0.44340378, 0.1925962 , 0.18793557],
       [0.45092128, 0.78761875, 0.82211291],
       [0.89324866, 0.74049824, 0.70062838]])

In [24]:
b = torch.rand(5, 3)

In [25]:
b


 0.9028  0.1386  0.4341
 0.3269  0.6736  0.9390
 0.4112  0.3746  0.0493
 0.7903  0.0281  0.7605
 0.8613  0.1931  0.1367
[torch.FloatTensor of size 5x3]

In [30]:
a.size, b.size()

(15, torch.Size([5, 3]))

### Operations

In [31]:
x = torch.rand(5, 3)
y = torch.rand(5, 3)

In [32]:
x


 0.4438  0.1859  0.0879
 0.5835  0.6989  0.2924
 0.7588  0.3981  0.5871
 0.4698  0.7241  0.3667
 0.3389  0.9591  0.5083
[torch.FloatTensor of size 5x3]

In [33]:
y


 0.9860  0.9415  0.2051
 0.9213  0.4411  0.6311
 0.3651  0.4292  0.7828
 0.6054  0.7004  0.3203
 0.2305  0.8613  0.5630
[torch.FloatTensor of size 5x3]

In [34]:
x + y


 1.4298  1.1274  0.2930
 1.5049  1.1400  0.9235
 1.1239  0.8274  1.3699
 1.0753  1.4245  0.6870
 0.5694  1.8204  1.0712
[torch.FloatTensor of size 5x3]

In [35]:
torch.add(x, y) # Functional form.


 1.4298  1.1274  0.2930
 1.5049  1.1400  0.9235
 1.1239  0.8274  1.3699
 1.0753  1.4245  0.6870
 0.5694  1.8204  1.0712
[torch.FloatTensor of size 5x3]

In [37]:
y.add_(x) # inplace


 1.4298  1.1274  0.2930
 1.5049  1.1400  0.9235
 1.1239  0.8274  1.3699
 1.0753  1.4245  0.6870
 0.5694  1.8204  1.0712
[torch.FloatTensor of size 5x3]

In [38]:
y


 1.4298  1.1274  0.2930
 1.5049  1.1400  0.9235
 1.1239  0.8274  1.3699
 1.0753  1.4245  0.6870
 0.5694  1.8204  1.0712
[torch.FloatTensor of size 5x3]

### Indexing as in numpy

In [40]:
x


 0.4438  0.1859  0.0879
 0.5835  0.6989  0.2924
 0.7588  0.3981  0.5871
 0.4698  0.7241  0.3667
 0.3389  0.9591  0.5083
[torch.FloatTensor of size 5x3]

In [41]:
x[:, 1]


 0.1859
 0.6989
 0.3981
 0.7241
 0.9591
[torch.FloatTensor of size 5]

In [45]:
x[2, :]


 0.7588
 0.3981
 0.5871
[torch.FloatTensor of size 3]

In [47]:
x[2, 1]

0.39814192056655884

### Reshape

In [51]:
x = torch.randn(4, 4)

In [52]:
x


 0.0276  0.9496  0.3056  0.7562
 1.0421 -0.2356  0.5074  1.2630
-0.2798 -0.9721  0.0598 -0.3875
 0.4416  1.2598  1.5673 -1.6656
[torch.FloatTensor of size 4x4]

In [50]:
x.view(16)


-0.1088
 0.5733
 1.6477
 0.5702
-0.6720
-1.0301
 0.1771
 0.1622
-0.4750
-0.1391
-0.7075
 2.2606
-1.3663
 1.5831
-0.9405
 0.9159
[torch.FloatTensor of size 16]

### Switch between tensor and ndarray

In [57]:
torch.zeros(5) # np.zeros


 0
 0
 0
 0
 0
[torch.FloatTensor of size 5]

In [58]:
a = torch.ones(5) # np.ones
a


 1
 1
 1
 1
 1
[torch.FloatTensor of size 5]

In [59]:
type(a)

torch.FloatTensor

In [63]:
b = a.numpy()

Fast, only metadata is moved.

In [69]:
type(b)

numpy.ndarray

In [70]:
b[0] += 1

In [71]:
a


 3
 1
 1
 1
 1
[torch.FloatTensor of size 5]

### Vice Versa

In [73]:
a = np.ones(5)

In [74]:
type(a)

numpy.ndarray

In [76]:
b = torch.from_numpy(a)

In [77]:
b


 1
 1
 1
 1
 1
[torch.DoubleTensor of size 5]

In [78]:
np.add(a, 1, out=a) # inline add 1

array([2., 2., 2., 2., 2.])

In [79]:
b


 2
 2
 2
 2
 2
[torch.DoubleTensor of size 5]

In [83]:
x = torch.rand(10)
y = torch.rand(10)

if torch.cuda.is_available():
    x = x.cuda()
    y = y.cuda()
    print(x + y)
else:
    print("cuda is not available")

cuda is not available
