# Basic PyTorch

In [1]:
import torch
import numpy as np

In [2]:
torch.__version__, np.__version__

('0.3.0.post4', '1.14.0')

### Basic n-dimensionaly array

In [3]:
a = np.ndarray((5, 3))

In [4]:
a

array([[-3.10503618e+231, -3.10503618e+231,  5.92878775e-323],
       [ 0.00000000e+000,  0.00000000e+000,  0.00000000e+000],
       [ 0.00000000e+000,  0.00000000e+000,  0.00000000e+000],
       [ 0.00000000e+000,  0.00000000e+000,  0.00000000e+000],
       [ 0.00000000e+000, -3.10503618e+231, -3.10503618e+231]])

In [5]:
a.shape

(5, 3)

In [6]:
b = torch.Tensor(5, 3)

In [7]:
b


 0.0000e+00 -1.5846e+29  1.0131e-07
 3.6902e+19  5.6052e-45  0.0000e+00
 0.0000e+00  0.0000e+00  0.0000e+00
 0.0000e+00  0.0000e+00  0.0000e+00
 0.0000e+00 -1.5846e+29  1.0149e-07
[torch.FloatTensor of size 5x3]

In [8]:
b.shape

torch.Size([5, 3])

### Random initialization

In [9]:
a = np.random.random((5, 3))

In [10]:
a

array([[0.61792576, 0.03393601, 0.19522195],
       [0.04562965, 0.5195018 , 0.86575594],
       [0.00146511, 0.02145967, 0.26285235],
       [0.45774233, 0.18455715, 0.87964256],
       [0.99254882, 0.82196785, 0.72118361]])

In [11]:
b = torch.rand(5, 3)

In [12]:
b


 0.6718  0.4183  0.4632
 0.4999  0.9510  0.7624
 0.3818  0.3289  0.7315
 0.4932  0.6714  0.6938
 0.3572  0.4711  0.7693
[torch.FloatTensor of size 5x3]

In [13]:
a.size, b.size()

(15, torch.Size([5, 3]))

### Operations

In [14]:
x = torch.rand(5, 3)
y = torch.rand(5, 3)

In [15]:
x


 0.8208  0.4917  0.7681
 0.0116  0.9630  0.2359
 0.4049  0.5573  0.2419
 0.4119  0.7565  0.2790
 0.1553  0.4533  0.5409
[torch.FloatTensor of size 5x3]

In [16]:
y


 0.0636  0.3108  0.5949
 0.0004  0.4941  0.6130
 0.5645  0.0025  0.7568
 0.5214  0.1616  0.7344
 0.0756  0.0099  0.8799
[torch.FloatTensor of size 5x3]

In [17]:
%timeit x + y

1.47 µs ± 47.6 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [18]:
%timeit torch.add(x, y) # Functional form.

1.81 µs ± 98.4 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [19]:
y.add_(x) # inplace


 0.8843  0.8025  1.3630
 0.0120  1.4571  0.8489
 0.9693  0.5599  0.9987
 0.9333  0.9180  1.0134
 0.2309  0.4632  1.4208
[torch.FloatTensor of size 5x3]

In [20]:
y


 0.8843  0.8025  1.3630
 0.0120  1.4571  0.8489
 0.9693  0.5599  0.9987
 0.9333  0.9180  1.0134
 0.2309  0.4632  1.4208
[torch.FloatTensor of size 5x3]

### Indexing as in numpy

In [21]:
x


 0.8208  0.4917  0.7681
 0.0116  0.9630  0.2359
 0.4049  0.5573  0.2419
 0.4119  0.7565  0.2790
 0.1553  0.4533  0.5409
[torch.FloatTensor of size 5x3]

In [22]:
x[:, 1]


 0.4917
 0.9630
 0.5573
 0.7565
 0.4533
[torch.FloatTensor of size 5]

In [23]:
x[2, :]


 0.4049
 0.5573
 0.2419
[torch.FloatTensor of size 3]

In [24]:
x[2, 1]

0.5573498010635376

### Reshape

In [25]:
x = torch.randn(4, 4)

In [26]:
x


 1.1083 -2.0260 -3.2308  0.4661
 0.5086 -0.0543 -1.6154 -0.0638
-0.6888  1.8562 -0.7367  0.3402
-1.3363 -0.2048 -1.5897 -0.1316
[torch.FloatTensor of size 4x4]

In [27]:
x.view(16) # np.reshape


 1.1083
-2.0260
-3.2308
 0.4661
 0.5086
-0.0543
-1.6154
-0.0638
-0.6888
 1.8562
-0.7367
 0.3402
-1.3363
-0.2048
-1.5897
-0.1316
[torch.FloatTensor of size 16]

### Switch between tensor and ndarray

In [28]:
torch.zeros(5) # np.zeros


 0
 0
 0
 0
 0
[torch.FloatTensor of size 5]

In [29]:
a = torch.ones(5) # np.ones
a


 1
 1
 1
 1
 1
[torch.FloatTensor of size 5]

In [30]:
type(a)

torch.FloatTensor

In [31]:
b = a.numpy()

Fast, only metadata is moved.

In [32]:
type(b)

numpy.ndarray

In [33]:
b[0] += 1

In [34]:
a


 2
 1
 1
 1
 1
[torch.FloatTensor of size 5]

### Vice Versa

In [35]:
a = np.ones(5)

In [36]:
type(a)

numpy.ndarray

In [37]:
b = torch.from_numpy(a)

In [38]:
b


 1
 1
 1
 1
 1
[torch.DoubleTensor of size 5]

In [39]:
np.add(a, 1, out=a) # inline add 1

array([2., 2., 2., 2., 2.])

In [40]:
b


 2
 2
 2
 2
 2
[torch.DoubleTensor of size 5]

In [41]:
x = torch.rand(10)
y = torch.rand(10)

if torch.cuda.is_available():
    x = x.cuda()
    y = y.cuda()
    print(x + y)
else:
    print("cuda is not available")

cuda is not available
